version: '3.8'

services:
  postgres-db:
    image: postgres:17-alpine
    container_name: file-system-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=file_system_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local 