# Production override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  app:
    read_only: false
    cap_add: [ SETUID, SETGID, DAC_READ_SEARCH ]
    environment:
      DD_SERVICE: file-system-app
      SPRING_PROFILES_ACTIVE: prod
      DD_ENV: prod
      AWS_PROFILE: ""
      AWS_EC2_METADATA_DISABLED: "false"
    volumes: []

  frontend:
    ports:
      - "80:80"

  datadog:
    environment:
      DD_ENV: prod
