version: '3.8'

services:
  postgres-db:
    image: postgres:17-alpine
    container_name: file-system-postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=file_system_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build: .
    image: file-system-app:local
    container_name: file-system-app
    depends_on:
      - postgres-db
    ports:
      - "8080:8080"
    env_file:
      - ./docs/env.example
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/file_system_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_PROFILES_ACTIVE: dev
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

volumes:
  postgres-data:
    driver: local 