# Production override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  app:
    environment:
      DD_SERVICE: file-system-app
      SPRING_PROFILES_ACTIVE: prod  # ← Override to prod profile
      DD_ENV: prod                  # ← Production Datadog environment
      # Add any other prod-specific env vars here
      
  datadog:
    environment:
      DD_ENV: prod

