# Production override for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up

services:
  app:
    read_only: false  # EC2 needs write access for temp files
    cap_add: [ SETUID, SETGID, DAC_READ_SEARCH ]
    volumes: []  # Remove AWS credentials mount
    environment:
      DD_SERVICE: file-system-app
      SPRING_PROFILES_ACTIVE: prod
      DD_ENV: prod
      # EC2: Use IAM role via IMDSv2 - override local dev AWS config
      AWS_PROFILE: ""  # Empty string tells AWS SDK to skip profile
      AWS_SHARED_CREDENTIALS_FILE: ""  # Empty string tells AWS SDK to skip file
      AWS_CONFIG_FILE: ""  # Empty string tells AWS SDK to skip file
      AWS_EC2_METADATA_DISABLED: "false"  # Enable IMDSv2
      AWS_SDK_LOAD_CONFIG: "true"

  frontend:
    ports:
      - "80:80"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./deployment/nginx/file-storage.conf:/etc/nginx/conf.d/default.conf:ro

  datadog:
    environment:
      DD_ENV: prod
