spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

server:
  forward-headers-strategy: framework

security:
  ratelimit:
    per-minute:
      upload: 5
      download: 60
      login: 5
  cors:
    allowed-origins:
      - https://app.example.com    # put your real frontend(s) here
      # - https://admin.example.com
    allowed-headers:
      - Authorization
      - Content-Type
      - X-Request-ID
      - Accept
    exposed-headers:
      - X-Request-ID
      - Content-Disposition
      - Location

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    export:
      otlp:
        enabled: true
        url: ${MANAGEMENT_OTLP_METRICS_EXPORT_URL:http://datadog:4318/v1/metrics}
        step: ${MANAGEMENT_OTLP_METRICS_EXPORT_STEP:60s}
    tags:
      application: ${spring.application.name}
      service: ${DD_SERVICE:file-system-app}
      env: ${DD_ENV:prod}
      version: ${DD_VERSION:1.0.0}
      region: ${AWS_REGION:us-east-1}
    distribution:
      percentiles-histogram:
        http.server.requests: true