spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
management:
  datadog:
    metrics:
      export:
        enabled: true
        api-key: ${DD_API_KEY}
        uri: ${DD_URI:https://api.datadoghq.com} 