name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java (Amazon Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'

      - name: Setup Gradle with caching
        uses: gradle/actions/setup-gradle@v3


      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run tests (with Gradle build cache and full stacktraces)
        env:
          CI: true
          TZ: UTC
        run: ./gradlew --no-daemon --build-cache --stacktrace --info test integrationTest

      - name: Upload test reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            build/reports/tests/**
            build/test-results/**
          if-no-files-found: ignore


